name: function-great-karolina0
namespace: default
runtime: nodejs14
source:
    sourceType: git
    url: https://bitbucket.com/pPrecel/kyma-function
    repository: function-great-karolina0
    reference: main
    baseDir: /code
