name: function-great-python39
namespace: default
runtime: python39
source:
    sourceType: git
    url: https://gitlab.com/pPrecel/kyma-function
    repository: function-great-python39
    reference: python
    baseDir: /code
