name: config-github-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: https://github.com/pPrecel/kyma-function
    repository: config-github-main
    reference: main
    baseDir: /code
