name: private-bitbucket-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: https://pPrecel@bitbucket.org/pPrecel/kyma-function.git
    repository: private-bitbucket
    reference: main
    baseDir: /code
    credentialsType: "basic"
    credentialsSecretName: "repos-basic-bitbucket"
