name: private-github-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: https://github.com/pPrecel/kyma-function
    repository: private-github
    reference: main
    baseDir: /code
    credentialsType: "basic"
    credentialsSecretName: "repos-basic-github"
