name: private-azure-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: https://kyma-wookiee@dev.azure.com/kyma-wookiee/kyma-function/_git/kyma-function
    repository: private-azure
    reference: main
    baseDir: /code
    credentialsType: "basic"
    credentialsSecretName: "repos-basic-azure"
