name: private-github-python
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: https://github.com/pPrecel/kyma-function
    repository: private-github
    reference: python
    baseDir: /code
    credentialsType: "basic"
    credentialsSecretName: "repos-basic-github"