name: private-bitbucket-python-tag
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: https://pPrecel@bitbucket.org/pPrecel/kyma-function.git
    repository: private-bitbucket
    reference: python-tag
    baseDir: /code
    credentialsType: "basic"
    credentialsSecretName: "repos-basic-bitbucket"
