name: public-gitlab-python-tag
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: https://gitlab.com/pPrecel/kyma-function
    repository: public-gitlab
    reference: python-tag
    baseDir: /code
