name: public-github-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: https://github.com/pPrecel/kyma-function
    repository: public-github
    reference: main
    baseDir: /code
