name: public-azure-python
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: https://kyma-wookiee@dev.azure.com/kyma-wookiee/kyma-function/_git/kyma-function
    repository: public-azure
    reference: python
    baseDir: /code
