name: public-bitbucket-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: https://pPrecel@bitbucket.org/pPrecel/kyma-function.git
    repository: public-bitbucket
    reference: main
    baseDir: /code
