name: ssh-azure-python-tag
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: git@ssh.dev.azure.com:v3/kyma-wookiee/kyma-function/kyma-function
    repository: ssh-azure
    reference: python-tag
    baseDir: /code
    credentialsType: "key"
    credentialsSecretName: "repos-ssh-key"
