name: ssh-azure-main
namespace: kyma-functions
runtime: nodejs14
source:
    sourceType: git
    url: git@ssh.dev.azure.com:v3/kyma-wookiee/kyma-function/kyma-function
    repository: ssh-azure
    reference: main
    baseDir: /code
    credentialsType: "key"
    credentialsSecretName: "repos-ssh-key"
