name: ssh-bitbucket-python-commit
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: git@bitbucket.org:pPrecel/kyma-function.git
    repository: ssh-bitbucket
    reference: 1d0444fe3a00ea364792d705593a995ee8ef0bf1
    baseDir: /code
    credentialsType: "key"
    credentialsSecretName: "repos-ssh-key"
