name: ssh-github-python
namespace: kyma-functions
runtime: python39
source:
    sourceType: git
    url: git@github.com:pPrecel/kyma-function.git
    repository: ssh-github
    reference: python
    baseDir: /code
    credentialsType: "key"
    credentialsSecretName: "repos-ssh-key"
